### PR TITLE
Fix bug 13655

### PR DESCRIPTION
**Pull request by oripka**

### CODE REVIEW

**Comment by hellais** [comment]
Awesome good stuff!

The only thing that needs to be added is the same filtering logic and checking for adding the tcp_connect field and then it should be all set to be merged.

**Comment by oripka** [comment]
Please take a look at the code above. It merges the two bugs 13640 and 13655. It also now correlates tcp connect and bridge measurements using the hashed fingerprint (it used to be done using the probe AS number, I am not sure what was the logic behind this). Using the hashed fingerprint we now can now output the information if a tcp connect measurement for the input bridge was successfull.

**Comment by hellais** [comment]
The reason why we did the check for the ASN is that the tcp connect test we are interested in connecting to the measurement in question are the ones that are performed from the same vantage point (hence have the same ASN) and were for the given input.

That checks needs to stay there as you will not find any tcp connect measurements being done from the control country (NL).

**Comment by oripka** [comment]
Ok, I'm going to do a new pull request to merge this into one commit

**Pull request closed without merging**
