### PR TITLE
Fix bug #13801 and use gzip instead of tar for report archival

### PR DESCRIPTION
**Pull request by oripka**
This should fix https://trac.torproject.org/projects/tor/ticket/13801. It also fixes some print statements.
Please review and pull ;)

### CODE REVIEW

**Comment by hellais** [comment]
Very cool! I will check this out :+1:

**Comment by hellais** [comment]
To merge this changes should also be done to: https://github.com/TheTorProject/ooni-pipeline/blob/master/ooni/pipeline/task/restore.py.

Probably we want restore.py to preserver backward compatibility and detect if the file in question is a `.tar.gz` or just a `gzip`.

**Comment by oripka** [comment]
Here is a fix for that. Note that we only detect this by file extension now. Detecting it using the mimetype would be a little bit more elaborate as one would need to extract the gz and then check if the resulting file is a tar.

**Comment by hellais** [comment]
Yes this is good now. I am going to proceed in merging this! Thanks!

**Pull request merged**
